// The SIMD-0385 golden vectors the wallets' v1 writer is tested against, and
// their deterministic test keys.
//
// test/fixtures/txv1-vectors.json is a verbatim copy of lazor-kit
// test-vectors/txv1.json (generated by lazor-kit scripts/txv1-vectors.mjs and
// checked there against @solana/kit 8.4.0 and @solana/web3.js 1.99.0).
// TXV1_VECTORS=<path> runs the tests against another copy, such as lazor-kit's own.
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { Keypair } from '@solana/web3.js';

export const VECTORS_PATH = process.env.TXV1_VECTORS || fileURLToPath(new URL('../fixtures/txv1-vectors.json', import.meta.url));
export const vectors = JSON.parse(readFileSync(VECTORS_PATH, 'utf8'));

const keys = new Map();
/** Key label L: the ed25519 key whose seed is sha256("lazorkit-txv1-vector:" + L). Test keys only. */
export function testKey(label) {
  if (!keys.has(label)) keys.set(label, Keypair.fromSeed(createHash('sha256').update(`lazorkit-txv1-vector:${label}`).digest()));
  return keys.get(label);
}

export const vector = (name) => {
  const v = vectors.vectors.find((x) => x.name === name);
  if (!v) throw new Error(`no vector ${name} in ${VECTORS_PATH}`);
  return v;
};

/** The vectors that fit v1, and so carry their unsigned wire bytes and signatures. */
export const fitting = () => vectors.vectors.filter((v) => v.expected.fits);

/**
 * What a wallet sends the paymaster: the vector's transaction with every
 * signature but the fee payer's (slot 0) in place.
 */
export function walletSent(v) {
  const e = v.expected;
  const wire = Buffer.from(e.unsigned, 'base64');
  e.signatures.forEach((s, i) => {
    if (i > 0 && s) wire.set(Buffer.from(s, 'base64'), e.messageLength + 64 * i);
  });
  return new Uint8Array(wire);
}

/** The vector's transaction with every signature the writer made, the fee payer's included. */
export function fullySigned(v) {
  const e = v.expected;
  const wire = Buffer.from(e.unsigned, 'base64');
  e.signatures.forEach((s, i) => {
    if (s) wire.set(Buffer.from(s, 'base64'), e.messageLength + 64 * i);
  });
  return new Uint8Array(wire);
}
