import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    testTimeout: 30_000,
    hookTimeout: 60_000,
    fileParallelism: false,
    // Disable per-file module isolation so the global ProtocolConfig
    // admin keypair generated by `tests/common.ts::setupTest()` is
    // shared across every test file (Approach A in the strict-fee
    // proposal). Without this, 12-protocol-fees would re-import
    // common.ts in a fresh module context, generate a new _adminKp,
    // and UpdateProtocol / WithdrawTreasury would fail with 4002
    // (InvalidProtocolAdmin) because the on-chain stored admin was
    // set by file 01's _adminKp.
    isolate: false,
  },
});
