import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['tests/**/*.test.ts'],
    environment: 'node',
    fileParallelism: false,
    // Disable per-file module isolation so the global ProtocolConfig
    // admin keypair generated by `tests/common.ts::setupTest()` is
    // shared across every test file. With isolation on, each file
    // would re-import common.ts in a fresh module context, generate
    // its own _adminSigner, and admin-only tests in 12-protocol-fees
    // would fail with 4002 (InvalidProtocolAdmin) because the on-chain
    // stored admin was set by file 01's _adminSigner.
    isolate: false,
    testTimeout: 60_000,
    hookTimeout: 60_000,
  },
});
